=== b-lieve/XMLschema/booksales.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XSD document created with EditiX XML Editor (http://www.editix.com) at Sun Apr 27 12:05:20 PDT 2014 -->
<!--
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
elementFormDefault="qualified">
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
-->


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">
<!--Author  simple elem-->
<xs:simpleType name="AuthorID">
	<xs:restriction base="xs:string"  >
		<xs:pattern value="[0-9]{2}[a-zA-Z][0-9]" />
	</xs:restriction>
</xs:simpleType>
<xs:element name="ID"  type="AuthorID" ></xs:element>

<xs:element name="Name"  >
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z][a-z]*\s([A-Z]\s)?[A-Z][a-z]*" />
		</xs:restriction>
	</xs:simpleType>
</xs:element>

<xs:element name="Email"  >
	<xs:simpleType>
		<xs:restriction base="xs:string">
		     <!-- too complex
		      <xs:pattern value="\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b"/>
		      -->
		      <xs:pattern value="(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})"/>
		</xs:restriction>
	</xs:simpleType>
</xs:element>

<xs:element name="Phone"  >
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="\([1-9][0-9]{2}\)\s[1-9][0-9]{2}\-[0-9]{4}" />
		</xs:restriction>
	</xs:simpleType>
</xs:element>
<!--Book simple elem -->
<xs:simpleType name="BookISBN">
		<xs:restriction base="xs:string">
			<xs:pattern value="[1-9][0-9]{8}[0-9X]" />
		</xs:restriction>
	</xs:simpleType>
<xs:element name="ISBN" type="BookISBN"></xs:element>


<xs:element name="Title" type="xs:string" >
</xs:element>


<!--Formats elem -->
<xs:simpleType name="BookFormatsFormat">
	<xs:restriction base="xs:string">
		<xs:pattern value="eBook|Paperback|Hardcover"/>
	</xs:restriction>
</xs:simpleType>
<xs:element name="Format"  type="BookFormatsFormat"></xs:element>

<xs:simpleType name="MSRP">
	<xs:restriction base="xs:decimal">
		<xs:minInclusive value="0"></xs:minInclusive>
	</xs:restriction>
</xs:simpleType>
<xs:element name="MSRP" type="MSRP" ></xs:element>

<xs:element name="WeeksBSL" type="xs:positiveInteger" ></xs:element>


<!--Book simple elem -->
<xs:element name="Retailer" type="xs:string"  ></xs:element>

<xs:simpleType name="Price">
	<xs:restriction base="xs:decimal">
		<xs:minInclusive value="0"></xs:minInclusive>
	</xs:restriction>
</xs:simpleType>
<xs:element name="Price" type="Price"></xs:element>
<xs:element name="UnitsSold"  type="xs:nonNegativeInteger" ></xs:element>


<xs:element name="Authors">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Author"  maxOccurs="unbounded"> 
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="ID"></xs:element>
						<xs:element ref="Name"></xs:element>
						<xs:element ref="Email"></xs:element>
						<xs:element ref="Phone"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:group name="SingleFormat">
	<xs:sequence>
		<xs:element ref="Format"></xs:element>
		<xs:element ref="MSRP"></xs:element>
	</xs:sequence>
</xs:group>
<xs:element name="Formats">
	<xs:complexType>
		<xs:sequence>
		 	<xs:group ref="SingleFormat" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>


<xs:element name="Books">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Book" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="ISBN"></xs:element>
						<xs:element ref="Title"></xs:element>
						<xs:element name="Author"  type="AuthorID" maxOccurs="unbounded"></xs:element>
						<xs:element ref="Formats" maxOccurs="unbounded"></xs:element>
						<xs:element ref="WeeksBSL" minOccurs="0"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="Sales" >
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Sale"  maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="Retailer"></xs:element>
						<xs:element ref="Price"></xs:element>
						<xs:element ref="UnitsSold"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="BookSales" >
	<xs:complexType>
		<xs:sequence>
			<xs:element name="BookSale"  maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Format" type="BookFormatsFormat"></xs:element>
						<xs:element ref="Sales"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="SalesInfo">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="OneSalesInfo" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Book" type="BookISBN"></xs:element>
						<xs:element ref="BookSales"></xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="booksales">
	<xs:complexType>
		<xs:all>
			<xs:element ref="Authors"></xs:element>
			<xs:element ref="Books"></xs:element>
			<xs:element ref="SalesInfo"></xs:element>
		</xs:all>
	</xs:complexType>
</xs:element>
</xs:schema>

=== b-lieve/XMLschema/booksales.xml
<?xml version="1.0"?>
<booksales       xmlns="http://www.w3schools.com"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	xs:schemaLocation="http://www.w3schools.com booksales.xsd">
<Authors>
	<Author>
		<ID>21f3</ID>
		<Name>Garth M Shelton</Name>
		<Email>gshelton@gmail.com</Email>
		<Phone>(470) 949-7859</Phone>
	</Author>
	<Author>
		<ID>14d3</ID>
		<Name>Beverly Rich</Name>
		<Email>beverly@deuce.net</Email>
		<Phone>(927) 407-2460</Phone>
	</Author>
	<Author>
		<ID>44K5</ID>
		<Name>Kibo X Carver</Name>
		<Email>carver@statichouse.com</Email>
		<Phone>(459) 376-6739</Phone>
	</Author>
	<Author>
		<ID>31R3</ID>
		<Name>Autumn Q Blevins</Name>
		<Email>aq@blevins.me</Email>
		<Phone>(996) 445-6213</Phone>
	</Author>
	<Author>
		<ID>19j6</ID>
		<Name>Amethyst D Fernandez</Name>
		<Email>ameth@deuce.net</Email>
		<Phone>(562) 559-8045</Phone>
	</Author>	
</Authors>
<Books>

	<Book>
		<ISBN>4756614025</ISBN>
		<Title>A Tale of Three Towns </Title>
		<Author>19j6</Author>
		<Formats>
			<Format>eBook</Format>
			<MSRP>12.99</MSRP>
		</Formats>
		<Formats>
			<Format>Hardcover</Format>
			<MSRP>24.00</MSRP>
		</Formats>
		<WeeksBSL>17</WeeksBSL>	
	</Book>
	<Book>
		<ISBN>4051865467</ISBN>
		<Title>Lord of the Crowns </Title>
		<Author>14d3</Author>
		<Author>19j6</Author>
		<Formats>
			<Format>Hardcover</Format>
			<MSRP>36.82</MSRP>
		</Formats>
		<Formats>
			<Format>eBook</Format>
			<MSRP>9.99</MSRP>
		</Formats>
		<WeeksBSL>17</WeeksBSL>	
	</Book>
	<Book>
		<ISBN>203387034X</ISBN>
		<Title>Of Cats and Men </Title>
		<Author>44K5</Author>
		<Formats>
			<Format>eBook</Format>
			<MSRP>4.99</MSRP>
		</Formats>
		<Formats>
			<Format>Hardcover</Format>
			<MSRP>26.49</MSRP>
		</Formats>
		<Formats>
			<Format>Paperback</Format>
			<MSRP>9.78</MSRP>
		</Formats>
		<WeeksBSL>52</WeeksBSL>	
	</Book>
	<Book>
		<ISBN>8496346865</ISBN>
		<Title>MacCharles</Title>
		<Author>21f3</Author>
		<Formats>
			<Format>eBook</Format>
			<MSRP>8.99</MSRP>
		</Formats>
		<Formats>
			<Format>Hardcover</Format>
			<MSRP>32.64</MSRP>
		</Formats>
	</Book>	
	<Book>
		<ISBN>1965685024</ISBN>
		<Title>Oliver Straight </Title>
		<Author>14d3</Author>
		<Formats>
			<Format>Paperback</Format>	
			<MSRP>8.99</MSRP>
		</Formats>
		<WeeksBSL>16</WeeksBSL>
	</Book>
	<Book>
		<ISBN>2031825889</ISBN>
		<Title>The Four Knights</Title>
		<Author>21f3</Author>
		<Author>31R3</Author>
		<Formats>
			<Format>Hardcover</Format>	
			<MSRP>22.73</MSRP>
		</Formats>
		<WeeksBSL>3</WeeksBSL>
	</Book>
	<Book>
		<ISBN>8020040696</ISBN>
		<Title>Paradise Found</Title>
		<Author>44K5</Author>
		<Author>31R3</Author>
		<Formats>
			<Format>Paperback</Format>	
			<MSRP>8.99</MSRP>
		</Formats>
		<Formats>
			<Format>Hardcover</Format>	
			<MSRP>22.73</MSRP>
		</Formats>
		<WeeksBSL>39</WeeksBSL>
	</Book>
	<Book>
		<ISBN>820778283X</ISBN>
		<Title>Twenty Shades of Cardinal </Title>
		<Author>31R3</Author>
		<Formats>
			<Format>eBook</Format>	
			<MSRP>6.49</MSRP>
		</Formats>
	</Book>

</Books>
<SalesInfo>
	<OneSalesInfo>
		<Book>203387034X</Book>
		<BookSales>
			<BookSale>
				<Format>eBook</Format>
				<Sales>
					<Sale>
						<Retailer>Amazon</Retailer>
						<Price>2.48</Price>
						<UnitsSold>200</UnitsSold>
					</Sale>
					<Sale>
						<Retailer>BN</Retailer>
						<Price>4.49</Price>
						<UnitsSold>173</UnitsSold>
					</Sale>
				</Sales>
			</BookSale>
			<BookSale>
				<Format>Hardcover</Format>
				<Sales>
					<Sale>
						<Retailer>Amazon</Retailer>
						<Price>24.99</Price>
						<UnitsSold>307</UnitsSold>
					</Sale>
					<Sale>
						<Retailer>BN</Retailer>
						<Price>24.99</Price>
						<UnitsSold>339</UnitsSold>
					</Sale>
				</Sales>				
			</BookSale>
		</BookSales>
	</OneSalesInfo>
	<OneSalesInfo>
		<Book>820778283X</Book>
		<BookSales>
			<BookSale>
				<Format>eBook</Format>
				<Sales>
					<Sale>
						<Retailer>BN</Retailer>
						<Price>3.25</Price>
						<UnitsSold>254</UnitsSold>
					</Sale>
					<Sale>
						<Retailer>Amazon</Retailer>
						<Price>5.00</Price>
						<UnitsSold>136</UnitsSold>
					</Sale>
				</Sales>
			</BookSale>
		</BookSales>
	</OneSalesInfo>
	<OneSalesInfo>
		<Book>4756614025</Book>
		<BookSales>
			<BookSale>
				<Format>eBook</Format>
				<Sales>
					<Sale>
						<Retailer>Amazon</Retailer>
						<Price>7.99</Price>
						<UnitsSold>162</UnitsSold>
					</Sale>

				</Sales>
			</BookSale>
			<BookSale>
				<Format>Hardcover</Format>
				<Sales>
					<Sale>
						<Retailer>Vromans</Retailer>
						<Price>16.74</Price>
						<UnitsSold>329</UnitsSold>
					</Sale>
				</Sales>				
			</BookSale>
		</BookSales>
	</OneSalesInfo>
	<OneSalesInfo>
		<Book>1965685024</Book>
		<BookSales>
			<BookSale>
				<Format>Paperback</Format>
				<Sales>
					<Sale>
						<Retailer>Amazon</Retailer>
						<Price>6.98</Price>
						<UnitsSold>73</UnitsSold>
					</Sale>
					<Sale>
						<Retailer>BN</Retailer>
						<Price>6.99</Price>
						<UnitsSold>93</UnitsSold>
					</Sale>
					<Sale>
						<Retailer>Vromans</Retailer>
						<Price>3.99</Price>
						<UnitsSold>200</UnitsSold>
					</Sale>
				</Sales>				
			</BookSale>
		</BookSales>
	</OneSalesInfo>
	<OneSalesInfo>
		<Book>4051865467</Book>
		<BookSales>
			<BookSale>
				<Format>Hardcover</Format>
				<Sales>
					<Sale>
						<Retailer>Vromans</Retailer>
						<Price>36.82</Price>
						<UnitsSold>135</UnitsSold>
					</Sale>
					<Sale>
						<Retailer>Amazon</Retailer>
						<Price>32.44</Price>
						<UnitsSold>164</UnitsSold>
					</Sale>
				</Sales>				
			</BookSale>
			<BookSale>
				<Format>Paperback</Format>
				<Sales>
					<Sale>
						<Retailer>Amazon</Retailer>
						<Price>8.99</Price>
						<UnitsSold>156</UnitsSold>
					</Sale>
					<Sale>
						<Retailer>BN</Retailer>
						<Price>3.26</Price>
						<UnitsSold>296</UnitsSold>
					</Sale>
				</Sales>				
			</BookSale>
		</BookSales>
	</OneSalesInfo>
	<OneSalesInfo>
		<Book>8496346865</Book>
		<BookSales>
			<BookSale>
				<Format>Hardcover</Format>
				<Sales>
					<Sale>
						<Retailer>Vromans</Retailer>
						<Price>29.99</Price>
						<UnitsSold>63</UnitsSold>
					</Sale>
				</Sales>
			</BookSale>
		</BookSales>
	</OneSalesInfo>
	<OneSalesInfo>
		<Book>8020040696</Book>
		<BookSales>
			<BookSale>
				<Format>Hardcover</Format>
				<Sales>
					<Sale>
						<Retailer>Vromans</Retailer>
						<Price>24.99</Price>
						<UnitsSold>273</UnitsSold>
					</Sale>
					<Sale>
						<Retailer>BN</Retailer>
						<Price>21.49</Price>
						<UnitsSold>394</UnitsSold>
					</Sale>
				</Sales>				
			</BookSale>
			<BookSale>
				<Format>Paperback</Format>
				<Sales>
					<Sale>
						<Retailer>Amazon</Retailer>
						<Price>8.99</Price>
						<UnitsSold>194</UnitsSold>
					</Sale>
					<Sale>
						<Retailer>BN</Retailer>
						<Price>7.99</Price>
						<UnitsSold>97</UnitsSold>
					</Sale>
				</Sales>				
			</BookSale>
		</BookSales>
	</OneSalesInfo>
</SalesInfo>
</booksales>
